# CHANGEME: Set these variable to your liking
title: ESP32 SmartPlug made for ESPHome
description: Smart Plug with ESP32 WROOM 32 and an embedded STHC3 temperature and humidity sensor.
theme: jekyll-theme-slate
