name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: rowi-plug.yaml
      name: ESP32 Smart Plug made for ESPHome (Kiwi Warmer Rowi) 
